### ISSUE TITLE
Validate a REST API response against the Swagger/OpenAPI spec

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-rest-4j#27]
Provide a method to validate a response against the specification.

A usable step would allow the validation of a response from integration and/or unit tests.

**Comment by stevehu** [comment]
@ddobrin Thanks a lot for raising this issue. Had a long discussion with one of your team members and I think it would help during the development cycle. I was too focused on the production runtime in the beginning and couldn't find a way to return the validation error within the normal response. I am more leaning to implement this in the client module at the moment and we can make it optional so that it can be turned off on production. Let's discuss the details once we meet.

**Comment by ddobrin** [comment]
Agreed.
This change needs to be implemented in the Client module, while retaining the ability to toggle its usage, for performance reasons in Production.

**Comment by ddobrin** [comment]
@stevehu : there are 3 cases where response validation against the spec can be performed:

1. client module
2. handler wired in the handler chain, on the provider side
3. utility module, on the provider side, which the microservice can invoke to validate the response.

My client wishes to retain both options [2,3], which will be used during development and testing.

**Note:**
This functionality needs to be enabled/disabled via configuration, as it is not recommended to be used in a production environment

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validate a REST API response against the Swagger/OpenAPI spec](https://trello.com/c/zRCyaqmA/83-validate-a-rest-api-response-against-the-swagger-openapi-spec)
